name: first-action
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: first-step
              uses: actions/hello-world-javascript-action@b8f604c84fc8cb0894b2e799b4f010e43794d95f
                with:
                    who-to-greet: Priya
              id: greet
            - name: second-step
              run: echo "${{steps.greet.outputs.time}}"